In [6]:
import numpy as np
import pandas as pd

In [10]:
ser = pd.Series(np.random.random(5), name = "Coluna 01")

In [11]:
ser

0    0.157552
1    0.132645
2    0.948675
3    0.282007
4    0.471890
Name: Coluna 01, dtype: float64

In [16]:
from pandas_datareader import data as wb

In [30]:
PG = wb.DataReader('PG', data_source = 'yahoo', start = '1995-1-1')

In [31]:
PG

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
1995-01-03,15.625000,15.437500,15.468750,15.593750,3318400.0,6.441071
1995-01-04,15.656250,15.312500,15.531250,15.468750,2218800.0,6.389442
1995-01-05,15.437500,15.218750,15.375000,15.250000,2319600.0,6.299082
1995-01-06,15.406250,15.156250,15.156250,15.281250,3438000.0,6.311993
1995-01-09,15.406250,15.187500,15.343750,15.218750,1795200.0,6.286175
1995-01-10,15.437500,15.187500,15.281250,15.406250,4364000.0,6.363626
1995-01-11,15.593750,15.375000,15.593750,15.375000,3738400.0,6.350714
1995-01-12,15.531250,15.312500,15.375000,15.531250,3307600.0,6.415256
1995-01-13,15.843750,15.531250,15.593750,15.625000,3992800.0,6.602774
1995-01-16,15.968750,15.750000,15.906250,15.750000,3677200.0,6.655601
1995-01-17,15.812500,15.656250,15.718750,15.812500,2437600.0,6.682010
1995-01-18,15.750000,15.437500,15.687500,15.468750,3535200.0,6.536748
1995-01-19,15.406250,15.343750,15.343750,15.406250,2491200.0,6.510336
1995-01-20,15.406250,15.250000,15.406250,15.343750,5130800.0,6.483925
1995-01-23,15.500000,15.187500,15.187500,15.500000,3147200.0,6.549954
1995-01-24,15.531250,15.375000,15.500000,15.468750,2016400.0,6.536748
1995-01-25,15.781250,15.437500,15.500000,15.687500,2802400.0,6.629185
1995-01-26,15.843750,15.687500,15.718750,15.750000,3124000.0,6.655601
1995-01-27,16.250000,15.812500,15.812500,16.187500,6247200.0,6.840477
1995-01-30,16.562500,16.093750,16.125000,16.437500,5226400.0,6.946117
1995-01-31,16.500000,16.281250,16.343750,16.281250,3934800.0,6.880093
1995-02-01,16.343750,15.937500,16.343750,15.968750,3047200.0,6.748035
1995-02-02,16.125000,15.875000,15.968750,16.093750,3810400.0,6.800859
1995-02-03,16.375000,16.187500,16.218750,16.250000,4442800.0,6.866884
1995-02-06,16.625000,16.281250,16.281250,16.625000,4003600.0,7.025350
1995-02-07,16.593750,16.406250,16.562500,16.593750,2380400.0,7.012147
1995-02-08,16.593750,16.406250,16.593750,16.406250,2481200.0,6.932914
1995-02-09,16.468750,16.312500,16.437500,16.375000,2143600.0,6.919710
1995-02-10,16.406250,16.156250,16.343750,16.343750,2445600.0,6.906503
1995-02-13,16.468750,16.312500,16.312500,16.468750,1726400.0,6.959328
...,...,...,...,...,...,...
2019-06-20,112.019997,110.500000,110.779999,111.739998,7044200.0,111.021019
2019-06-21,112.470001,111.019997,111.620003,111.199997,13799400.0,110.484497
2019-06-24,112.500000,111.400002,111.820000,112.330002,5518100.0,111.607231
2019-06-25,112.629997,111.309998,112.110001,111.720001,6805600.0,111.001152
2019-06-26,111.440002,109.660004,111.389999,109.730003,7170300.0,109.023956
2019-06-27,110.269997,109.290001,109.919998,109.779999,5613300.0,109.073631
2019-06-28,111.959999,109.019997,111.860001,109.650002,12152000.0,108.944473
2019-07-01,110.699997,109.610001,109.919998,110.489998,6775900.0,109.779060
2019-07-02,111.500000,110.290001,110.610001,111.480003,6578200.0,110.762695
2019-07-03,114.269997,111.839996,111.959999,114.080002,6223300.0,113.345970
2019-07-05,113.449997,112.230003,112.970001,113.150002,8694800.0,112.421951
2019-07-08,114.230003,113.300003,113.339996,114.050003,5317800.0,113.316162
2019-07-09,113.910004,112.320000,113.900002,112.910004,7537700.0,112.183495
2019-07-10,114.500000,113.400002,113.459999,113.750000,5600700.0,113.018089
2019-07-11,114.400002,113.440002,113.660004,114.379997,4625300.0,113.644035
2019-07-12,115.209999,114.070000,114.070000,114.989998,7058600.0,114.250107
2019-07-15,115.879997,114.790001,115.070000,115.480003,6240700.0,114.736961
2019-07-16,116.519997,115.449997,115.720001,115.889999,7644300.0,115.144318
2019-07-17,116.290001,115.730003,115.730003,115.940002,7861700.0,115.194000
2019-07-18,115.769997,114.790001,114.930000,115.440002,5828700.0,115.440002
2019-07-19,115.949997,115.010002,115.500000,115.010002,6547000.0,115.010002
2019-07-22,115.449997,114.580002,115.040001,115.300003,4018800.0,115.300003
2019-07-23,116.050003,113.839996,115.709999,113.849998,8194600.0,113.849998
2019-07-24,113.879997,112.279999,113.849998,112.599998,9635900.0,112.599998
2019-07-25,112.980003,111.379997,111.480003,112.769997,7809400.0,112.769997
2019-07-26,114.879997,112.879997,113.209999,114.730003,5559600.0,114.730003
2019-07-29,116.209999,114.620003,114.730003,116.000000,7768700.0,116.000000
2019-07-30,121.760002,118.800003,119.820000,120.410004,18788800.0,120.410004
2019-07-31,120.680000,117.070000,119.660004,118.040001,12641800.0,118.040001
2019-08-01,119.169998,116.730003,118.559998,116.730003,11305200.0,116.730003

In [32]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6189 entries, 1995-01-03 to 2019-08-01
Data columns (total 6 columns):
High         6189 non-null float64
Low          6189 non-null float64
Open         6189 non-null float64
Close        6189 non-null float64
Volume       6189 non-null float64
Adj Close    6189 non-null float64
dtypes: float64(6)
memory usage: 338.5 KB

In [35]:
PG.head(20)

                High       Low      Open     Close     Volume  Adj Close
Date
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   6.441071
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   6.389442
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   6.299082
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   6.311993
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   6.286175
1995-01-10  15.43750  15.18750  15.28125  15.40625  4364000.0   6.363626
1995-01-11  15.59375  15.37500  15.59375  15.37500  3738400.0   6.350714
1995-01-12  15.53125  15.31250  15.37500  15.53125  3307600.0   6.415256
1995-01-13  15.84375  15.53125  15.59375  15.62500  3992800.0   6.602774
1995-01-16  15.96875  15.75000  15.90625  15.75000  3677200.0   6.655601
1995-01-17  15.81250  15.65625  15.71875  15.81250  2437600.0   6.682010
1995-01-18  15.75000  15.43750  15.68750  15.46875  3535200.0   6.536748
1995-01-19  15.40625  15.34375  15.34375  15.40625  2491200.0   6.510336
1995-01-20  15.40625  15.25000  15.40625  15.34375  5130800.0   6.483925
1995-01-23  15.50000  15.18750  15.18750  15.50000  3147200.0   6.549954
1995-01-24  15.53125  15.37500  15.50000  15.46875  2016400.0   6.536748
1995-01-25  15.78125  15.43750  15.50000  15.68750  2802400.0   6.629185
1995-01-26  15.84375  15.68750  15.71875  15.75000  3124000.0   6.655601
1995-01-27  16.25000  15.81250  15.81250  16.18750  6247200.0   6.840477
1995-01-30  16.56250  16.09375  16.12500  16.43750  5226400.0   6.946117

In [36]:
PG.tail(20)

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2019-07-05,113.449997,112.230003,112.970001,113.150002,8694800.0,112.421951
2019-07-08,114.230003,113.300003,113.339996,114.050003,5317800.0,113.316162
2019-07-09,113.910004,112.320000,113.900002,112.910004,7537700.0,112.183495
2019-07-10,114.500000,113.400002,113.459999,113.750000,5600700.0,113.018089
2019-07-11,114.400002,113.440002,113.660004,114.379997,4625300.0,113.644035
2019-07-12,115.209999,114.070000,114.070000,114.989998,7058600.0,114.250107
2019-07-15,115.879997,114.790001,115.070000,115.480003,6240700.0,114.736961
2019-07-16,116.519997,115.449997,115.720001,115.889999,7644300.0,115.144318
2019-07-17,116.290001,115.730003,115.730003,115.940002,7861700.0,115.194000
2019-07-18,115.769997,114.790001,114.930000,115.440002,5828700.0,115.440002
2019-07-19,115.949997,115.010002,115.500000,115.010002,6547000.0,115.010002
2019-07-22,115.449997,114.580002,115.040001,115.300003,4018800.0,115.300003
2019-07-23,116.050003,113.839996,115.709999,113.849998,8194600.0,113.849998
2019-07-24,113.879997,112.279999,113.849998,112.599998,9635900.0,112.599998
2019-07-25,112.980003,111.379997,111.480003,112.769997,7809400.0,112.769997
2019-07-26,114.879997,112.879997,113.209999,114.730003,5559600.0,114.730003
2019-07-29,116.209999,114.620003,114.730003,116.000000,7768700.0,116.000000
2019-07-30,121.760002,118.800003,119.820000,120.410004,18788800.0,120.410004
2019-07-31,120.680000,117.070000,119.660004,118.040001,12641800.0,118.040001
2019-08-01,119.169998,116.730003,118.559998,116.730003,11305200.0,116.730003

In [39]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source = 'yahoo', start = '1995-1-1')['Adj Close']

In [40]:
new_data.tail()

                    PG        MSFT          T     F     GE
Date
2019-07-26  114.730003  141.339996  34.150002  9.57  10.51
2019-07-29  116.000000  141.029999  34.340000  9.60  10.38
2019-07-30  120.410004  140.350006  34.180000  9.55  10.52
2019-07-31  118.040001  136.270004  34.049999  9.53  10.45
2019-08-01  116.730003  138.059998  34.119999  9.31  10.08